
package view;
import Controller.AllObjectModel06955;
import Controller.PraktikanController06955;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class AslabGUI{

    private static PraktikanController06955 praktikan = new PraktikanController06955();
    JFrame Aslab = new JFrame();
    JTable tabelprak = new JTable();
    JScrollPane scrollaslab = new JScrollPane(tabelprak);
    JButton back,verif;
    JLabel admin,npmlabel,passlabel;
    JTextField npmtext,passtext;
    
    public AslabGUI() {
        Aslab.setSize(650,500);
        Aslab.setLayout(null);
        Aslab.getContentPane().setBackground(Color.PINK);
        
        admin = new JLabel("Admin");
        admin.setBounds(250,30,200,30);
        admin.setFont(new Font("Times New Roman",Font.BOLD,40));
        Aslab.add(admin);
        
        scrollaslab.setBounds(30,100,570,200);
        tabelprak.setModel(praktikan.daftarprak());
        Aslab.add(scrollaslab);
        
        npmlabel = new JLabel("NPM");
        npmlabel.setBounds(50,320,100,30);
        Aslab.add(npmlabel);
        
        npmtext = new JTextField();
        npmtext.setBounds(50,350,100,30);
        Aslab.add(npmtext);
        
        passlabel = new JLabel("password");
        passlabel.setBounds(200,320,100,30);
        Aslab.add(passlabel);
        
        passtext = new JTextField();
        passtext.setBounds(200,350,100,30);
        Aslab.add(passtext);
        
        verif = new JButton("Verif");
        verif.setBounds(350,350,100,30);
        verif.setBackground(Color.GREEN);
        Aslab.add(verif);
        
        back = new JButton("back");
        back.setBounds(50,400,100,30);
        back.setBackground(Color.RED);
        Aslab.add(back);
        
        Aslab.setLocationRelativeTo(null);
        Aslab.setVisible(true);
        Aslab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        back.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                Aslab.dispose();
                GUI men = new GUI();
            }
        });
        
        verif.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                String npm = npmtext.getText();
                String pass = passtext.getText();
                int index = AllObjectModel06955.daftarprakmodel.cekData(npm, pass);
                allobjctrl06955.admin.updateIsVerified(index, allobjctrl06955.praktikan.showDaftarPrak(index).getIndexPrak(), allobjctrl06955.praktikan.showDaftarPrak(index).getPraktikan());
                tabelprak.setModel(praktikan.daftarprak());
            }
        });
        
        tabelprak.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int i = tabelprak.getSelectedRow();
                npmtext.setText(allobjctrl06955.praktikan.daftarprak().getValueAt(i, 0).toString());
                passtext.setText(allobjctrl06955.praktikan.daftarprak().getValueAt(i, 1).toString());
            }         
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AslabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AslabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AslabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AslabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AslabGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
