
package view;

import Entity.PraktikumEntity06955;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class PraktikanGUI{

    JFrame Praktikan = new JFrame();
    JButton back,daftarbtn;
    JTextArea area = new JTextArea();
    JLabel datadiri,daftarprak;
    JComboBox pilprak = new JComboBox(PraktikumEntity06955.nama);
    int cek = allobjctrl06955.praktikan.cekDaftarprak(allobjctrl06955.praktikan.praktikanEntity().getNpm());
    
    public PraktikanGUI() {
        Praktikan.setSize(720,600);
        Praktikan.setLayout(null);
        Praktikan.getContentPane().setBackground(Color.PINK);
        datadiri = new JLabel("Data Praktikan");
        datadiri.setFont(new Font("Times New Roman",Font.BOLD,30));
        datadiri.setBounds(90,30,200,30);
        Praktikan.add(datadiri);
        
        area.setBounds(30,90,400,300);
        Praktikan.add(area);
        
        daftarprak = new JLabel("Daftar Praktikum");
        daftarprak.setBounds(450,30,250,30);
        daftarprak.setFont(new Font("Times New Roman",Font.BOLD,30));
        Praktikan.add(daftarprak);
        
        pilprak.setBounds(450,90,230,30);
        Praktikan.add(pilprak);
        
        daftarbtn = new JButton("Daftar");
        daftarbtn.setBounds(500,200,100,30);
        daftarbtn.setBackground(Color.GREEN);
        Praktikan.add(daftarbtn);
        
        back = new JButton("back");
        back.setBounds(30,500,100,30);
        back.setBackground(Color.RED);
        Praktikan.add(back);
        
        Praktikan.setVisible(true);
        Praktikan.setLocationRelativeTo(null);
        Praktikan.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        if(cek==-1){
            JOptionPane.showMessageDialog(null,"Belum daftar praktikum","Information",JOptionPane.INFORMATION_MESSAGE);
        }else if(cek==-2){
            JOptionPane.showMessageDialog(null,"Belum daftar praktikum","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            area.setText(datapraktikan());
        }
        daftarbtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                int indexprak = pilprak.getSelectedIndex();
                allobjctrl06955.praktikan.daftarPraktikum(indexprak, allobjctrl06955.praktikan.getData(), false);
                area.setText(datapraktikan());
            }
        });
        
        back.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                Praktikan.dispose();
                GUI men = new GUI();
            }
        });
    }

    String datapraktikan(){
        int cekk = allobjctrl06955.praktikan.cekDaftarprak(allobjctrl06955.praktikan.praktikanEntity().getNpm());
        String cekverif;
        if(allobjctrl06955.praktikan.showDaftarPrak(cekk).isVerified()==false){
            cekverif = "Belum Verifikasi";
        }else{
            cekverif = "Sudah Verifikasi";
        }
        String text = ""
                + "NPM           = " + allobjctrl06955.praktikan.showDaftarPrak(cekk).getPraktikan().getNpm() + "\n"
                + "Nama          = " + allobjctrl06955.praktikan.showDaftarPrak(cekk).getPraktikan().getNama() + "\n"
                + "No Telp       = " + allobjctrl06955.praktikan.showDaftarPrak(cekk).getPraktikan().getNo_telp() + "\n"
                + "Tanggal Lahir = " + new SimpleDateFormat("dd-MM-yyyy").format(allobjctrl06955.praktikan.showDaftarPrak(cekk).getPraktikan().getTglLahir())+ "\n"
                + "Verifikasi    = " + cekverif + "\n"
                + "Kelas         = " + allobjctrl06955.praktikan.showDaftarPrak(cekk).getPraktikan().getKelas() + "\n"
                + "Praktikum     = " + PraktikumEntity06955.nama[allobjctrl06955.praktikan.showDaftarPrak(cekk).getIndexPrak()];
        return text;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
/*                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PraktikanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PraktikanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PraktikanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PraktikanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {
/*            public void run() {
/*                new PraktikanGUI().setVisible(true);
            }
 /*       });
/*    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
/*}
